name: Playwright Tests

on:
  workflow_dispatch:       # Manual trigger via GitHub UI
  schedule:                # Every 1 hour (UTC)
    - cron: '0 * * * *'
  push:                    # On push to any branch
    branches:
      - '**'
  pull_request:            # On PR to any branch
    branches:
      - '**'

jobs:
  functional-tests:
    name: Functional UI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Functional UI Tests
        run: npx playwright test --project=ui || true

      - name: Upload Functional Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: functional-ui-report
          path: playwright-report/

  visual-tests:
    name: Visual Regression Tests
    runs-on: ubuntu-latest
    needs: functional-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Visual Regression Tests
        run: npx playwright test tests/visual.spec.mjs || true

      - name: Upload Visual Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visual-report
          path: playwright-report/

      - name: Upload Screenshot Diffs (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visual-diffs
          path: screenshots/diffs/
