name: Playwright Tests

on:
  workflow_dispatch:     # Manual trigger via GitHub UI
  schedule:              # Every 1 hour (UTC)
    - cron: '0 * * * *'
  push:                  # On push to any branch
    branches:
      - '**'
  pull_request:          # On PR to any branch
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run regular Playwright tests
        run: npx playwright test

      - name: Run Visual Regression Tests
        env:
          URL1: ${{ secrets.URL1 }}
          URL2: ${{ secrets.URL2 }}
        run: npx playwright test tests/visual.spec.js

      - name: Debug – list files
        if: always()
        run: ls -R

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Upload Visual Diffs (if any)
        if: failure()  # Only if visual test fails
        uses: actions/upload-artifact@v4
        with:
          name: visual-diffs
          path: screenshots/diffs/
