name: UI Functional Tests.

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  functional-tests:
    name: Functional UI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Functional UI Tests
        run: npx playwright test --project=ui || true

      - name: Upload Functional Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: functional-ui-report
          path: playwright-report/
