name: Visual Regression Tests

on:
  schedule:
    - cron: '0 * * * *'     # Runs every hour
  workflow_dispatch:        # Allow manual trigger

jobs:
  visual-tests:
    name: Visual Regression Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Visual Regression Tests
        run: npx playwright test tests/visual.spec.mjs || true

      - name: Upload Visual Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visual-report
          path: playwright-report/

      - name: Upload Screenshot Diffs (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visual-diffs
          path: screenshots/diffs/
